### ISSUE TITLE
KLAS 강의 공지사항 페이지 다크모드 적용

### ISSUE THREAD

**Issue by pkeugine** [teamkw/PangBot-Web-Extension#6]
목표
---
강의 공지사항 페이지까지 다크모드 확대

상황
---
메인 페이지와 동일한 부분 일부 다크모드 적용됨. 하지만 동일하지 않은 부분 변경 필요.

**Comment by ckdals4600** [comment]
@pkeugine 제가 이 기능을 하고 싶습니다!

**Comment by pkeugine** [comment]
@ckdals4600 네 부탁드립니다! 질문이 있다면 언제든지 말해주세요.
